<template>
    <v-container fluid>
        <v-row>
            <v-col cols="12" md="8" offset-md="2">
                <v-card class="px-4 py-4">
                    <v-row>
                        <v-col cols="12" md="6">
                            <v-card-title class="text-h6">
                                What is a carbon footprint?
                            </v-card-title>
                            <v-card-text>
                                A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and
                                methane)
                                that are generated by our actions.
                                <br>
                                The average carbon footprint for a person in the United States is 16 tons, one of the
                                highest rates
                                in the world. Globally, the average carbon footprint is closer to 4 tons. To have the best
                                chance of
                                avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year
                                needs to
                                drop to under 2 tons by 2050.
                                <br>
                                <br>
                                <p class="text-caption">
                                    (Source: <a
                                        href="https://www.nature.org/en-us/get-involved/how-to-help/carbon-footprint-calculator/">https://www.nature.org/carbon-footprint-calculator</a>)
                                </p>
                            </v-card-text>

                        </v-col>
                        <v-col cols="12" md="6">
                            <v-card-title class="text-h6">
                                Carbon Footprint Tracker
                            </v-card-title>
                            <v-card-text>
                                <v-form>
                                    <v-text-field v-model="electricityUsage" label="Electricity usage (kWh)"
                                        type="number"></v-text-field>
                                    <v-text-field v-model="gasUsage" label="Gas usage (therms)"
                                        type="number"></v-text-field>
                                    <v-text-field v-model="waterUsage" label="Water usage (gallons)"
                                        type="number"></v-text-field>
                                    <v-btn @click="calculateCarbonFootprint">Calculate</v-btn>
                                </v-form>
                            </v-card-text>
                        </v-col>
                    </v-row>
                </v-card>
            </v-col>
        </v-row>
        <v-row>
            <v-col cols="12" md="8" offset-md="2">
                <v-card class="px-4">
                    <v-card-title class="text-h6">
                        Suggestions for You
                    </v-card-title>
                    <v-card-text>
                        <v-list lines="one">
                            <v-list-item v-for="suggestion in suggestions" :key="suggestion">
                                ✔ {{ suggestion }}
                            </v-list-item>
                        </v-list>
                    </v-card-text>
                </v-card>
            </v-col>
        </v-row>
    </v-container>
</template>

<script setup>
import { ref } from 'vue';


const electricityUsage = ref(null);
const gasUsage = ref(null);
const waterUsage = ref(null);
const suggestions = ref([]);


const calculateCarbonFootprint = () => {
    const electricityFootprint = electricityUsage.value * 0.4536;
    const gasFootprint = gasUsage.value * 0.005302;
    const waterFootprint = waterUsage.value * 0.000264172;

    const totalFootprint = electricityFootprint + gasFootprint + waterFootprint;

    if (totalFootprint < 10) {
        suggestions.value = [
            "Switch to LED light bulbs",
            "Install a programmable thermostat",
            "Fix leaks in plumbing",
        ];
    } else if (totalFootprint < 20) {
        suggestions.value = [
            "Invest in energy-efficient appliances",
            "Use public transportation or carpool",
            "Buy carbon offsets",
        ];
    } else {
        suggestions.value = [
            "Install solar panels or wind turbines",
            "Reduce meat consumption",
            "Use reusable bags, water bottles, and other items",
        ];
    }
}
</script>
